### ISSUE TITLE
'function' object has no attribute 'get_shape'

### ISSUE THREAD

**Issue by Bonsen** [mkocabas/focal-loss-keras#14]
model.compile(loss=focal_loss, optimizer=sgd, metrics=[my_iou_metric])

  File "~/.local/lib/python3.6/site-packages/keras/engine/training.py", line 830, in compile
    sample_weight, mask)
  File "~/.local/lib/python3.6/site-packages/keras/engine/training.py", line 442, in weighted
    ndim = K.ndim(score_array)
  File "~/.local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 610, in ndim
    dims = x.get_shape()._dims
AttributeError: 'function' object has no attribute 'get_shape'

**Comment by fffupeng** [comment]
I have the same problem. Did you have fixed it ? @Bonsen

**Comment by Ynakatsuka** [comment]
This code works for me.
```
def focal_loss(y_true, y_pred, gamma=2., alpha=.25):
    pt_1 = tf.where(tf.equal(y_true, 1), y_pred, tf.ones_like(y_pred))
    pt_0 = tf.where(tf.equal(y_true, 0), y_pred, tf.zeros_like(y_pred))
    return -K.sum(alpha * K.pow(1. - pt_1, gamma) * K.log(pt_1))-K.sum((1-alpha) * K.pow( pt_0, gamma) * K.log(1. - pt_0))
```

**Comment by chestnut111** [comment]
You should use like this:
model_prn.compile(optimizer=optimizer, loss=[focal_loss(alpha=.25, gamma=2)])

**Comment by BovineEnthusiast** [comment]
The correct solution has already been said above, but to explain it, `focal_loss` is a function that returns the actual loss function (`focal_loss_fixed`), hence why you need to call it. It's kind of like a loss function generator.

**Comment by mkocabas** [comment]
Closing the issue, feel free to open it.
