### ISSUE TITLE
Focal Loss is Huge

### ISSUE THREAD

**Issue by nectario** [mkocabas/focal-loss-keras#18]
Focal loss is huge. Why is that?

For example: loss: 38107.2309

**Comment by hemmer** [comment]
Probably just because it isn't normalised by the number of pixels anywhere (only K.sum is used). 

EDIT: see #16

**Comment by capilano** [comment]
Use reduce_sum instead of K.sum

**Comment by mkocabas** [comment]
https://github.com/mkocabas/focal-loss-keras/commit/5852a8857014ba05eedbc8ffab264f955acb16b6 should solve the issue
